

const BISHOP_VIEW_MULTIPLY = 1.5;
const BISHOP_TAG_MULTIPLY = 0.6;
const KING_VIEW_MULTIPLY = 1.5
const KING_TAG_MULTIPLY = 1.5;


module.exports = {
    BISHOP_VIEW_MULTIPLY,
    BISHOP_TAG_MULTIPLY,
    KING_VIEW_MULTIPLY,
    KING_TAG_MULTIPLY
}